### ISSUE TITLE
warning messages: 1: In balance.cluster(all.sig, cc = cc, cluster.cutoff = cluster.cutoff,  :   User defined max super cluster number is larger than real value, will refine it to (n - 1)!

### ISSUE THREAD

**Issue by cyth01** [bioinformatist/CrossICC#7]
数据集中包括三个批次样本，list包含三个批次时可以正常运行
当list中只有一个批次时运行过程中出现warning，并停止运行，无法得到结果
>CrossICC.input <- list(bt1)
>test <- CrossICC(CrossICC.input)
Only one matrix detected. MergeMaid will not work. Will skip cross analysis.
Wed Apr 26 23:59:29 2023 -- Pre-processing data 
Wed Apr 26 23:59:29 2023 -- Removing features with no variance 
Wed Apr 26 23:59:29 2023 -- Performing MAD filtering 
Wed Apr 26 23:59:29 2023 -- Scaling 
No study names provided or something goes wrong with your study names. Will use auto-generated study names instead.
Wed Apr 26 23:59:29 2023 -- start iteration: 1 
41 genes were engaged in this iteration.
Wed Apr 26 23:59:34 2023 -- start iteration: 2 
40 genes were engaged in this iteration.
Wed Apr 26 23:59:40 2023 -- start iteration: 3 
38 genes were engaged in this iteration.
Wed Apr 26 23:59:45 2023 -- start iteration: 4 
38 genes were engaged in this iteration.
Error in CrossICC(CrossICC.input) : Result file already existed!
In addition: Warning messages:
1: In balance.cluster(all.sig, cc = cc, cluster.cutoff = cluster.cutoff,  :
  User defined max super cluster number is larger than real value, will refine it to (n - 1)!
2: In balance.cluster(all.sig, cc = cc, cluster.cutoff = cluster.cutoff,  :
  User defined max super cluster number is larger than real value, will refine it to (n - 1)!
3: In balance.cluster(all.sig, cc = cc, cluster.cutoff = cluster.cutoff,  :
  User defined max super cluster number is larger than real value, will refine it to (n - 1)!
4: In balance.cluster(all.sig, cc = cc, cluster.cutoff = cluster.cutoff,  :
  User defined max super cluster number is larger than real value, will refine it to (n - 1)!
![image](https://user-images.githubusercontent.com/131895344/234634082-d23c1dee-8f1c-4fd2-a22c-7a7e41a7fb6b.png)

**Comment by likelet** [comment]
这不是报错，这是提示你 结果已经生成了，没有报错，你看下你home目录下的.crossICC.object

**Comment by likelet** [comment]
https://github.com/bioinformatist/CrossICC/blob/ceb710e54186a98b5c077bc5417e9a1301cb1d14/R/CrossICC.R#L277 看下这个代码 就知道了

或者把这个文件删掉 再跑一遍。因为crossicc本身不是专门给一个矩阵跑的，所以这里设置了结果重复的问题

**Comment by cyth01** [comment]
找到结果了，确实是在home目录里面了，只顾着看rstudio中的变量了，没注意看目录情况。真的太感谢了，麻烦您了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qi ***@***.***&gt;; 
发送时间: 2023年4月27日(星期四) 凌晨0:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bioinformatist/CrossICC] warning messages: 1: In balance.cluster(all.sig, cc = cc, cluster.cutoff = cluster.cutoff,  :   User defined max super cluster number is larger than real value, will refine it to (n - 1)! (Issue #7)





 
https://github.com/bioinformatist/CrossICC/blob/ceb710e54186a98b5c077bc5417e9a1301cb1d14/R/CrossICC.R#L277 看下这个代码 就知道了
